version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: dino
    ports:
      - 5432:5432
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d


